### ISSUE TITLE
What caused this error？    KeyError: 'loss'

### ISSUE THREAD

**Issue by panzhengsen** [zj-zhang/AMBER#22]
I believe there is no problem with my data set construction.
The error message is as follows:

`
['traindata', 'trainxdata']
['validdata', 'validxdata']
BUILDING
----------
controller = GeneralController
modeler = EnasCnnModelBuilder
knowledge = zero
reward = LossAucReward
manager = EnasManager
time budget set to: 24:00:00
env_type = EnasTrainEnv
 Trial -1: Start training model with sample_arc...
Traceback (most recent call last):
  File "amber_deepsea.py", line 124, in <module>
    amb.run()
  File "/home/zhouss/AMBER/amber/wrapper.py", line 104, in run
    self.env.train()
  File "/home/zhouss/AMBER/amber/architect/trainEnv.py", line 418, in train
    self.manager.get_rewards(trial=-i, model_arc=None, nsteps=warmup_nsteps)
  File "/home/zhouss/AMBER/amber/architect/manager.py", line 544, in get_rewards
    verbose=self.verbose,
  File "/home/zhouss/AMBER/amber/modeler/child.py", line 743, in fit
    prog = ", ".join(["%s=%.4f" % (name, hist.history[name][-1]) for name in to_print])
  File "/home/zhouss/AMBER/amber/modeler/child.py", line 743, in <listcomp>
    prog = ", ".join(["%s=%.4f" % (name, hist.history[name][-1]) for name in to_print])
KeyError: 'loss'
`

**Comment by zj-zhang** [comment]
It seems you might have specified a batch size that is larger than the total data size, so that the loss is not computed by call back function by the end of the epoch, because no epoch can run.
Since you already checked `hist.history`, could you also confirm the value of `nsteps` in the same for loop? If you see `nsteps=0`, then changing the `batch_size` to a smaller value should fix it.

**Comment by panzhengsen** [comment]
Thank you for your reply.
That is, the batchsize in model_builder is larger than child_batchsize, which has nothing to do with the batchsize in the controller.

**Comment by zj-zhang** [comment]
@panzhengsen Yes it's the `child_batchsize` too large. It has nothing to do with the controller's batch size. You can confirm this by examining the values of `nsteps`.

**Comment by zj-zhang** [comment]
I see, can you read in your training and validation data (for example, by `hdf5` or `pickle`) without using `EncodedGenome`? Right now it's not tested for compatibility with Enas modeler (and seems it's incompatible), and thus the issue. 

As an example, the input to DeepSEA train/val data are two numpy arrays: 
https://github.com/zj-zhang/AMBER/blob/master/examples/amber_deepsea.py#L97

**Comment by panzhengsen** [comment]
ok.
The function of `rna_data_and_feature.py` file is to turn fa file into h5py file.
Because the h5py file format of the training set and the test set are the same, I print the output of the test set.
I use `read.py` to read the test set data in h5py format.
The two python files mentioned above and the read results are placed in `result.zip`
And I printed `EncodedGenome`, the output is as follows:
<amber.utils.sequences.EncodedGenome object at 0x7fc009bc3ed0
[result.zip](https://github.com/zj-zhang/AMBER/files/7210577/result.zip)
>
